package ExceptionHandling;

public class Exception {

	public static void main(String[] args) {
	
		// TODO Auto-generated method stub
		int i=10;
		try {
			System.out.println(10/0);
		} catch (ArithmeticException e) {
			// TODO Auto-generated catch block
			System.out.println(e.getMessage());
			throw new ArithmeticException("/ by zero");
		}
		

	}

}
